name: Snyk

on:
  push:
    branches: [ main, jd-snyk-action ]
  workflow_dispatch:

jobs:
  snyk:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: SBT - Run Snyk to check for vulnerabilities
        uses: snyk/actions/scala@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=the-guardian-cuu --project-name=${{ github.repository }} --file=./build.sbt
          command: monitor
          
      - name: Yarn - Run Snyk to check for vulnerabilities
        uses: snyk/actions/scala@0.3.0
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --org=the-guardian-cuu --project-name=${{ github.repository }} --file=./frontend/package.json
          command: monitor
          
